inherit_from: .rubocop_todo.yml

Encoding:
  Enabled: false

Metrics/ClassLength:
  CountComments: false

AllCops:
  Exclude:
    - contentful-management.gemspec
    - bin/cma-console
    - spec/**/*
    - examples/**/*
    - Guardfile
    - Gemfile
    - Rakefile

Metrics/LineLength:
  Max: 135

Metrics/ClassLength:
  Max: 250
